from __future__ import annotations

import re
import warnings
from collections.abc import Callable, Sequence
from dataclasses import dataclass
from typing import Any

import torch
import torch.nn as nn

from onelife.litellm_utils import (
    GeminiLiteLlmParams,
    LiteLlmMessage,
    LiteLlmParamsBase,
    LiteLlmRequest,
)
from onelife.local_code_execution import ExecWithLimitedNamespace
from onelife.mujoco_dataset import MuJoCoTransitions

from .core import LawPrediction, TransitionBatch
from .laws import (
    ContinuousLaw,
    JointLimitVelocityLaw,
    KinematicPositionLaw,
    LinearVelocityLaw,
)
from .program import SymbolicProgram


@dataclass(frozen=True)
class LLMLawSynthesisConfig:
    """Configuration for offline LLM symbolic-law synthesis."""

    env_id: str
    dt: float = 0.05
    sample_count: int = 8
    max_prompt_float_precision: int = 4
    max_tokens: int = 2500
    confidence: float = 1.0
    validation_sample_count: int = 256
    max_validation_mse_ratio: float = 1.25
    validation_abs_tolerance: float = 1e-3


@dataclass(frozen=True)
class LLMSynthesizedLaws:
    """Validated law bundle generated by an LLM."""

    laws: tuple[ContinuousLaw, ...]
    code: str
    prompt: str
    raw_response: str

    def build_program(self, state_dim: int) -> SymbolicProgram:
        return SymbolicProgram(state_dim=state_dim, laws=self.laws)


LLMClient = Callable[[LiteLlmRequest], Any]


class LLMSymbolicLawSynthesizer:
    """
    Offline LLM proposer for executable continuous symbolic laws.

    The generated code is not used during the neural forward pass. It is compiled
    once, validated as ContinuousLaw instances, and then passed into SymbolicProgram.
    """

    def __init__(
        self,
        llm_params: LiteLlmParamsBase | None = None,
        llm_client: LLMClient | None = None,
    ) -> None:
        self.llm_params = llm_params
        self.llm_client = llm_client or (lambda request: request())

    def synthesize_from_mujoco_dataset(
        self,
        transitions: MuJoCoTransitions,
        config: LLMLawSynthesisConfig,
    ) -> LLMSynthesizedLaws:
        states, actions, next_states = transitions.to_torch()
        batch = TransitionBatch(states=states, actions=actions, next_states=next_states)
        return self.synthesize_from_batch(batch, config)

    def synthesize_from_batch(
        self,
        batch: TransitionBatch,
        config: LLMLawSynthesisConfig,
    ) -> LLMSynthesizedLaws:
        if batch.states.ndim != 2:
            raise ValueError("batch.states must have shape [num_steps, state_dim]")
        if batch.actions.ndim != 2:
            raise ValueError("batch.actions must have shape [num_steps, action_dim]")
        if batch.next_states.shape != batch.states.shape:
            raise ValueError("batch.next_states must match batch.states shape")

        state_dim = int(batch.states.shape[1])
        action_dim = int(batch.actions.shape[1])
        prompt = build_mujoco_law_synthesis_prompt(
            batch=batch,
            state_dim=state_dim,
            action_dim=action_dim,
            config=config,
        )
        request = LiteLlmRequest(
            messages=[
                LiteLlmMessage(
                    role="system",
                    content=_SYSTEM_PROMPT,
                ),
                LiteLlmMessage(
                    role="user",
                    content=prompt,
                ),
            ],
            params=self._params_with_config(config),
        )
        response = self.llm_client(request)
        raw_response = _response_text(response)
        code = extract_python_code(raw_response)
        laws = compile_synthesized_laws(
            code=code,
            state_dim=state_dim,
            action_dim=action_dim,
            dt=config.dt,
            default_confidence=config.confidence,
            validation_batch=batch,
            validation_sample_count=config.validation_sample_count,
            max_validation_mse_ratio=config.max_validation_mse_ratio,
            validation_abs_tolerance=config.validation_abs_tolerance,
        )
        return LLMSynthesizedLaws(
            laws=tuple(laws),
            code=code,
            prompt=prompt,
            raw_response=raw_response,
        )

    def _params_with_config(self, config: LLMLawSynthesisConfig) -> LiteLlmParamsBase:
        params = self.llm_params or GeminiLiteLlmParams()
        if params.max_tokens is None:
            params = params.model_copy(update={"max_tokens": config.max_tokens})
        return params


def build_mujoco_law_synthesis_prompt(
    batch: TransitionBatch,
    state_dim: int,
    action_dim: int,
    config: LLMLawSynthesisConfig,
) -> str:
    samples = _format_transition_samples(batch, config)
    return f"""
We are building a hybrid MuJoCo world model:
    s_next_hat = F_program(s, a) + R_theta(s, a, F_program(s, a))

Your task is to propose executable symbolic/code laws for F_program.

Environment: {config.env_id}
State dimension: {state_dim}
Action dimension: {action_dim}
Integration dt: {config.dt}

Return only Python code inside one ```python fenced block.
Do not import anything. The execution namespace already contains:
    torch, nn, ContinuousLaw, LawPrediction,
    KinematicPositionLaw, LinearVelocityLaw, JointLimitVelocityLaw

The code must define:

def build_laws(state_dim: int, action_dim: int, dt: float, confidence: float) -> list[ContinuousLaw]:
    ...

Each custom law must inherit ContinuousLaw and implement:
    precondition(self, state: torch.Tensor, action: torch.Tensor) -> bool
    predict(self, state: torch.Tensor, action: torch.Tensor) -> LawPrediction

Important tensor shape contract:
    state is one single 1D tensor with shape [{state_dim}]
    action is one single 1D tensor with shape [{action_dim}]
Do not use batched indexing such as state[:, i] or action[:, i].

LawPrediction fields:
    indices: torch.LongTensor containing next-state dimensions predicted by the law
    values: torch.Tensor with predicted values for those dimensions
    confidence: torch.Tensor same shape as values
    law_name: str

Prefer compact interpretable laws. Use the neural residual for dimensions you cannot
explain confidently. Avoid predicting every dimension with weak made-up rules.

Observed transitions:
{samples}
""".strip()


def compile_synthesized_laws(
    code: str,
    state_dim: int,
    action_dim: int,
    dt: float,
    default_confidence: float = 1.0,
    validation_batch: TransitionBatch | None = None,
    validation_sample_count: int = 256,
    max_validation_mse_ratio: float = 1.25,
    validation_abs_tolerance: float = 1e-3,
) -> list[ContinuousLaw]:
    executor = ExecWithLimitedNamespace(
        allowed_names={
            "torch",
            "nn",
            "ContinuousLaw",
            "LawPrediction",
            "KinematicPositionLaw",
            "LinearVelocityLaw",
            "JointLimitVelocityLaw",
        },
        inherited_scope={
            "torch": torch,
            "nn": nn,
            "ContinuousLaw": ContinuousLaw,
            "LawPrediction": LawPrediction,
            "KinematicPositionLaw": KinematicPositionLaw,
            "LinearVelocityLaw": LinearVelocityLaw,
            "JointLimitVelocityLaw": JointLimitVelocityLaw,
        },
    )
    executor(code)
    build_laws = executor.namespace.get("build_laws")
    if not callable(build_laws):
        raise ValueError("LLM code must define callable build_laws(...)")

    raw_laws = build_laws(
        int(state_dim),
        int(action_dim),
        float(dt),
        float(default_confidence),
    )
    if not isinstance(raw_laws, list):
        raise TypeError("build_laws(...) must return list[ContinuousLaw]")
    laws: list[ContinuousLaw] = []
    for law in raw_laws:
        if not isinstance(law, ContinuousLaw):
            raise TypeError(
                "build_laws(...) returned an object that is not a ContinuousLaw: "
                f"{type(law).__name__}"
            )
        try:
            _smoke_test_law(law, state_dim, action_dim)
            if validation_batch is not None:
                _validate_law_against_batch(
                    law=law,
                    batch=validation_batch,
                    sample_count=validation_sample_count,
                    max_mse_ratio=max_validation_mse_ratio,
                    abs_tolerance=validation_abs_tolerance,
                )
        except Exception as exc:
            warnings.warn(
                "Skipping invalid LLM-generated law "
                f"{law.law_name}: {type(exc).__name__}: {exc}",
                RuntimeWarning,
                stacklevel=2,
            )
            continue
        laws.append(law)
    return laws


def _validate_law_against_batch(
    law: ContinuousLaw,
    batch: TransitionBatch,
    sample_count: int,
    max_mse_ratio: float,
    abs_tolerance: float,
) -> None:
    limit = min(int(sample_count), int(batch.states.shape[0]))
    if limit <= 0:
        return

    law_squared_errors: list[torch.Tensor] = []
    identity_squared_errors: list[torch.Tensor] = []
    active_count = 0
    for idx in range(limit):
        state = batch.states[idx]
        action = batch.actions[idx]
        if not law.precondition(state, action):
            continue
        prediction = law.predict(state, action)
        _validate_prediction_shape(prediction, state_dim=int(batch.states.shape[1]))
        indices = prediction.indices.to(dtype=torch.long, device=batch.states.device)
        values = prediction.values.to(dtype=batch.states.dtype, device=batch.states.device)
        target_values = batch.next_states[idx, indices]
        identity_values = batch.states[idx, indices]
        law_squared_errors.append((values - target_values).square())
        identity_squared_errors.append((identity_values - target_values).square())
        active_count += 1

    if active_count == 0:
        raise ValueError(f"{law.law_name} was never active on validation samples")

    law_mse = torch.cat(law_squared_errors).mean()
    identity_mse = torch.cat(identity_squared_errors).mean()
    allowed_mse = identity_mse * float(max_mse_ratio) + float(abs_tolerance)
    if law_mse > allowed_mse:
        raise ValueError(
            f"{law.law_name} failed validation: law_mse={float(law_mse):.6g}, "
            f"identity_mse={float(identity_mse):.6g}, "
            f"allowed_mse={float(allowed_mse):.6g}"
        )


def extract_python_code(raw_response: str) -> str:
    fenced = re.search(r"```(?:python)?\s*(.*?)```", raw_response, flags=re.DOTALL)
    if fenced is not None:
        return fenced.group(1).strip()
    return raw_response.strip()


def _smoke_test_law(law: ContinuousLaw, state_dim: int, action_dim: int) -> None:
    _smoke_test_law_on_inputs(
        law,
        torch.zeros(state_dim, dtype=torch.float32),
        torch.zeros(action_dim, dtype=torch.float32),
    )
    _smoke_test_law_on_inputs(
        law,
        torch.linspace(-0.5, 0.5, state_dim, dtype=torch.float32),
        torch.linspace(-0.25, 0.25, action_dim, dtype=torch.float32),
    )


def _smoke_test_law_on_inputs(
    law: ContinuousLaw,
    state: torch.Tensor,
    action: torch.Tensor,
) -> None:
    if not law.precondition(state, action):
        return
    prediction = law.predict(state, action)
    _validate_prediction_shape(prediction, state_dim=int(state.shape[0]))


def _validate_prediction_shape(prediction: LawPrediction, state_dim: int) -> None:
    if prediction.indices.ndim != 1:
        raise ValueError(f"{prediction.law_name} returned non-1D indices")
    if prediction.values.shape != prediction.indices.shape:
        raise ValueError(f"{prediction.law_name} returned values with wrong shape")
    if prediction.confidence.shape != prediction.indices.shape:
        raise ValueError(f"{prediction.law_name} returned confidence with wrong shape")
    if prediction.values.dtype not in (torch.float16, torch.float32, torch.float64):
        raise ValueError(f"{prediction.law_name} returned non-floating values")
    if not torch.all(torch.isfinite(prediction.values)):
        raise ValueError(f"{prediction.law_name} returned non-finite values")
    if torch.any(prediction.indices < 0) or torch.any(prediction.indices >= state_dim):
        raise ValueError(f"{prediction.law_name} returned out-of-range indices")


def _response_text(response: Any) -> str:
    choices = getattr(response, "choices", None)
    if not choices:
        raise ValueError("LLM response does not contain choices")
    choice = choices[0]
    message = getattr(choice, "message", None)
    if isinstance(message, dict):
        content = message.get("content")
    else:
        content = getattr(message, "content", None)
    if content is None:
        content = getattr(choice, "text", None)
    if not isinstance(content, str) or not content.strip():
        raise ValueError("LLM response does not contain text content")
    return content


def _format_transition_samples(
    batch: TransitionBatch,
    config: LLMLawSynthesisConfig,
) -> str:
    num_samples = min(int(config.sample_count), int(batch.states.shape[0]))
    if num_samples <= 0:
        raise ValueError("cannot synthesize laws from an empty transition batch")
    lines = []
    for idx in range(num_samples):
        state = _round_vector(batch.states[idx], config.max_prompt_float_precision)
        action = _round_vector(batch.actions[idx], config.max_prompt_float_precision)
        next_state = _round_vector(
            batch.next_states[idx],
            config.max_prompt_float_precision,
        )
        delta = _round_vector(
            batch.next_states[idx] - batch.states[idx],
            config.max_prompt_float_precision,
        )
        lines.append(
            f"- sample {idx}: state={state}; action={action}; "
            f"next_state={next_state}; delta={delta}"
        )
    return "\n".join(lines)


def _round_vector(values: torch.Tensor, precision: int) -> list[float]:
    detached = values.detach().cpu().to(torch.float32).tolist()
    return [round(float(value), precision) for value in detached]


_SYSTEM_PROMPT = """
You write concise, safe Python for a MuJoCo symbolic dynamics module.
Return only law code. No prose. No imports. No file, network, shell, or eval calls.
Use the provided ContinuousLaw/LawPrediction API exactly.
""".strip()
